### ISSUE TITLE
Inclined-Elliptic Frozen Orbit Performance

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#13]
Regarding the analysis of the performance of the lunar inclined-elliptic frozen orbit constellation proposed by Ely in "Stable Constellations of Frozen Elliptical Inclined Lunar Orbits" with respect to solar power satellite service to a lunar south pole target.

**Comment by darianvp** [comment]
The original constellation published by Ely in 2005 is based on a stable orbit which provides 100% communications coverage to the lunar south pole.

[StableConstellationsofFrozenEllipiticalInclinedLunarOrbits2005.pdf](https://github.com/MatthewGrim/Lunar_SPS/files/2141258/StableConstellationsofFrozenEllipiticalInclinedLunarOrbits2005.pdf)

The performance of this orbit/constellation with respect to the solar power satellite concept has the following performance metrics:

(0deg)
Single SPS active time: 40.9175 %
Single SPS blackout time: 11.5867 %

(0deg, 180deg)
Double SPS active time: 52.455 %
Double SPS blackout time: 0.0492 %

(0deg, 120deg, 240deg)
Triple SPS active time: 52.473 %
Triple SPS blackout time: 0.0312 %

The blackout events at the target under service of the above constellations are as follows:
![frozen_orbit_jun27](https://user-images.githubusercontent.com/38875772/41975950-18d9dc10-7a1c-11e8-808e-42ce958d8145.png)

The performance of the orbit itself with respect to the mean wireless power transmission metrics (assuming 1 m receiver radius, with 40% efficiency):

Optimum transmitter radius: 157.0 cm
Mean link efficiency: 20.29 %
Mean power delivered: 1217.49 W

**Comment by darianvp** [comment]
With this orbital configuration, a near complete suppression of blackout events is possible. The benefits of the proposed orbit is high stability. It also contributes an additional example toward the rule of thumb for constellation size offered in Issue #12.

The main issue with this constellation concept is the altitude of the orbit, which is higher than is allowable by the pointing accuracy convention which has been taken thus far in the project (1e-6 rad). Due to the large semi-major axis, relatively large eccentricity, and inclination of the orbit, the mean range from the satellite to the target is on the order of 8950 km for each access period. Considering Gaussian beam diffraction for a 1070nm transmitter with the above mentioned optimized transmitter aperture size, a pointing accuracy on the order of 1e-7 would be required to accurately target a rover with a 1m receiver radius. This can be improved by increasing the size of the transmitter aperture - an aperture radius of 10m leads to a pointing accuracy of 1e-6. However increasing the transmitter aperture to the size which accommodates the pointing requirement leads to a violation of the minimum power requirement received at the target.



Passing this issue to @MatthewGrim for review. Suggest additional performance metrics you would find useful to investigate.

**Comment by darianvp** [comment]
Since the frozen orbit design from Ely is based on the gravitational perturbations due to the Earth, the perturbations will generally shrink for a lower altitude orbit. Hypothetically a lower altitude orbit, aligned in the same plane as the orbit proposed by Ely could also be stable. This is because the other orbital elements are related to the stability of the orbit, but the semi-major axis is selected such that the field-of-view to the south pole requirement is satisfied (Equation 19 in Ely). The reduction in semi-major axis of the orbit is limited to roughly 4400 km by the orbital perigee altitude. The performance of this lowest possible altitude orbit is very similar to the orbit proposed by Ely:

Single SPS active time: 37.8851 %
Single SPS blackout time: 14.6191 %

Double SPS active time: 52.428 %
Double SPS blackout time: 0.0762 %

Triple SPS active time: 51.798 %
Triple SPS blackout time: 0.7062 %

Optimal aperture radius: 126.71 cm
Mean pointing error: 1.736e-07 rad

The inclination of the orbit leads to such a large increase in mean range (in comparison to the polar orbit) that the pointing error constraint is still violated. Furthermore, the frozen orbit stability has associated with it variations (but not divergences) in semi-major axis and eccentricity. These variations may cause a low altitude orbit to crash.

**Comment by MatthewGrim** [comment]
@darianvp only comment on this is whether using a microwave wavelength might make the orbit more manageable. This makes the pointing accuracy less of an issue, but if increasing aperture size makes the power requirement unmanageable then I am guessing the same will be true for microwaves, due to increased beam spreading?
