### ISSUE TITLE
Update past python files so that they still run

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#14]
Some of the old scripts replicating Brandhorst figure 3 are broken, I think because there are functions with the same name in general_SPS_functions and DVP_general_SPS_functions. It might be an idea to merge these two files to avoid future problems if this is the case.

This issue should document the necessary refactoring to make sure past studies can still be run with the code as it stands.

This is a low priority issue, but needs to be done at some point.

**Comment by MatthewGrim** [comment]
## Known broken scripts
**002** - Replicate_Fig3_Access_Times.py, replicate_brandhorst_fig3.py and Fig3_Comparison.py.
**003** - SPS_Optimal_Orbit_Verification.py

**Comment by MatthewGrim** [comment]
While scanning these old studies, it would also be worth fixing the headers of files, and naming conventions. Maybe adding a README for each directory. This might help clarify the meaning of each study better.

Some figures could also use a title to clarify what they're showing.

**Comment by darianvp** [comment]
Most recent commit refers to files in 003. Commit previous to that refers to 002.

**Comment by darianvp** [comment]
I am also using this issue to push commits related to updating/restructuring of the repository and updating/renaming individual files.

**Comment by darianvp** [comment]
All scripts have been tested and the broken scripts have been updated/fixed - closing this issue.
