### ISSUE TITLE
Assess Thermal Load at Receiver

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#15]
In this issue I analyze the anticipated thermal load at the receiver.

**Comment by darianvp** [comment]
Minimum allowable flux required to power a target is given by the equation:

![codecogseqn](https://user-images.githubusercontent.com/38875772/42377503-d3091048-8123-11e8-9c00-eded79fe29c4.gif)

where the efficiency and radius of the receiver are in the denominator. The flux requirement is only dependent on the choice of target. 

Under the assumption that the target system is designed to accommodate the necessary rejection of heat generated by solar radiance (AM0 = 1367 W/m2), then reducing the transmitter flux to that order of magnitude, while still meeting the minimum flux requirement defined in the above equation, should lead to a heat load at the target should be manageable. 

To incorporate this in the SPS design tool, I calculate the minimum flux requirement of the target, then convert that to a minimum transmitter power in order to reduce the heat load on the target. This is done after optimizing the orbit so that the maximum range of the optimized orbit can be used to estimate the maximum beam spot size, and thus minimum beam flux at the target.

Of the three target choices so far available in the model, the minimum flux requirements are:
1. Sorato --> 1.25 AM0 
2. AMALIA --> 0.23 AM0
3. Curiosity --> 0.16 AM0

By optimizing the transmitter power such that the mean-minimum power delivered is equal to the operational power of the rover, the mean heat load at the reciever will be slightly larger (due to the mean being larger than the mean-minimum power) than 1.2 times the operational power of the rover (based on 40% receiver efficiency). 

In the case that the minimum transmitter power determined for the optimized design is lower within the power range of a smaller transmitter option, the smaller option is selected. The generator size is chosen to provide enough power for the minimum transmitter power

**Comment by MatthewGrim** [comment]
@darianvp just to clarify, you're assuming the same pv conversion efficiency here? What value did you choose?

**Comment by darianvp** [comment]
@MatthewGrim same pv efficiency, assumed to be 40% at the moment.

**Comment by darianvp** [comment]
Closing this issue since it has been addressed as best as possible, incorporating only minimal knowledge of the detailed properties of the target.
