### ISSUE TITLE
Quantify Station-Keeping Opportunities

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#16]
In this issue I assess the opportunities for the SPS to perform station keeping maneuvers around the moon.

**Comment by darianvp** [comment]
Gravitational perturbations in lunar orbits are exerted by the irregularities in the moon's gravitational field and by the Earth. Station-keeping would be necessary in order to maintain an optimized lunar orbit for an SPS system. In initial analysis, station keeping is assumed to be performed using an electronic propulsion system, since the solar array used to generate power for the SPS could be used to support high-power electric propulsion as well.

The first step is determining events during which the SPS could perform station keeping maneuvers. These events are defined by the following:

- SPS is out of range of target and thus will not be providing power service
- SPS is sunlit, and can thus generate power for electric propulsion system

Taking the sum of the duration of all of these events provides an approximation of the total time available for performing high power EP maneuvers.

High performance thrust metric for electric propulsion systems from Fabien Marguet is k = 1N / 20 kW (verify in literature). By taking the mass, m, of the generator/transmitter combo, the power available from the solar array generator, Pgen, and the total amount of time available for station-keeping, T, the total available delta v impulse available throughout an entire simulation period can be estimated:

![codecogseqn 1](https://user-images.githubusercontent.com/38875772/42386890-0bcb261a-8141-11e8-97f8-2adc4e0feab1.gif)

This quantity is currently evaluated in the constrained SPS design tool. An interesting development with respect to this metric would be to relating it to the anticipated rate of change of the SPS orbital elements in order to assess the ability of the system to maintain is orbit long-term.

**Comment by darianvp** [comment]
![station_keeping_300peri3000apo](https://user-images.githubusercontent.com/38875772/42456530-70fd479c-8395-11e8-81af-2ac79eb24ad0.png)

The above plot is an example of all of the station keeping opportunities for a polar lunar orbit with 300 km perigee and 3000 km apogee. The total duration of station keeping events is 3647 hours per year.

**Comment by MatthewGrim** [comment]
This seems like a really good start, but you're right it needs to be linked to the orbital stability somehow. Doing this across the two year time span is ambitious. Maybe you can do something simpler, by estimating how much delta v is needed to get from the equatorial orbit that the perturbations are taking the satellite towards, back to the desired elliptical orbit. If you can estimate how many times the orbit would degrade to its equatorial state, and compare this to the number of times you can correct it, that might be a good first punt. It's not fullproof fair enough, but if there is significant variation between these numbers, it might be reasonable to trust. 

The fuel rate will also be important to assess, but this is again getting more detailed.

**Comment by darianvp** [comment]
@MatthewGrim 
From Spacecraft Dynamics and Control: A Practical Engineering Approach by Marcel J. Sidi (pg. 69) the delta v required to shift the argument of perigee of an orbit, maintaining all other parameters, is given by the equation:

![codecogseqn 2](https://user-images.githubusercontent.com/38875772/42509940-c3246ed4-844d-11e8-9ec6-c78113619e34.gif)

I have implemented this equation into the SPS design tool to estimate the amount orbital maintenance delta v required to negate the yearly skew in argument of perigee characteristic of the chosen SPS orbit. 

I think that a useful next step is reformulating the constraint on skew in argument of perigee into a constraint on the delta v required to maintain the orbit. This can be a user selected threshold, or a predetermined threshold where orbits for which the station keeping opportunities as defined above can not generate sufficient delta v in order to maintain the orbit are removed. However, based on a few tests I have done, it seems likely that this tight of a constraint may remove all design points since the above equation evaluates to quite high delta v requirements for the orbits we are considering. In many cases, the available delta v from EP accounts for approximately half of the necessary delta v.

There is a discrepancy with the drift in argument of perigee for circular orbits:
Fundamentally, there is a drift in the argument of perigee, however practically it no influence on SPS performance since there is no difference in apogee/perigee altitude. Therefore should I set dwdt = 0 in this case? Or keep the actual value?

**Comment by darianvp** [comment]
![station_keeping_equatorial_jul11](https://user-images.githubusercontent.com/38875772/42560406-db291b8e-84f6-11e8-84aa-28c00d3ab12c.png)
![station_keeping_polar_jul11](https://user-images.githubusercontent.com/38875772/42560407-db4438d8-84f6-11e8-874d-526fa375b7d5.png)

**Comment by darianvp** [comment]
Concerning difference between the available delta v for orbital maintanence with electric propulsion system and required delta v for argument of perigee drift, both as defined above.

In the case of the polar orbit configuration the difference of these two values is plotted below, where designs for which the delta v provided by electric propulsion is not sufficient to maintain the orbit are removed. The remaining values indicated the delta v margin provided by the assumed EP system (considering what is shown is required delta v minus available delta v).

![station_keeping_polar_jul11](https://user-images.githubusercontent.com/38875772/42563705-2b2978c4-84ff-11e8-9698-0c03c2ab036e.png)


For the equatorial case, the available delta v for exceeds what is necessary for all orbits (the removed data points corresponds to orbits with no active times).:

![station_keeping_equatorial_jul11](https://user-images.githubusercontent.com/38875772/42563866-90ee2b8c-84ff-11e8-82e1-f40842c236d1.png)

**Comment by darianvp** [comment]
Evaluating the margin between the available and required delta v is the new design variable regarding orbital stability. For a link-efficiency optimized design, the delta v margin imposes a lower bound constraint on the size of the solar array generator. By equating the required and available delta v equations, decomposing the mass into transmitter and generator mass, then solving for the generator power:

![codecogseqn 3](https://user-images.githubusercontent.com/38875772/42581736-bd61111a-852d-11e8-84b9-64a606845c74.gif)

Thus in optimization of the transmitter, the size of the generator is minimized to a size that is large enough to provide power for the optimized transmitter power and to bring the delta v margin to a value greater than or equal to zero.

**Comment by darianvp** [comment]
![sps_design_optimization_fd](https://user-images.githubusercontent.com/38875772/42619842-76de8920-85b9-11e8-83e7-4652d579c242.jpg)

**Comment by darianvp** [comment]
Due to the nature of the maneuver required to adjust the argument of perigee of an orbit, the impulse to change the orbit can only be applied at the two points at which the original and final orbits intersect. Therefore there are two opportunities to thrust each orbit. If each impulse takes a duration delta-t, the total delta v available (assuming that these points are always sunlit):

![codecogseqn 21](https://user-images.githubusercontent.com/38875772/42943976-ae6f87da-8b64-11e8-86ab-59e58952fb7b.gif)

where Ttot is the total duration of the simulation, P is the orbit period, PTTR is the power-to-thrust-ratio (20 kW / 1N) and Pg is the power available from the generator.
