### ISSUE TITLE
Equatorial Orbit - Constrained SPS Design Tool

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#17]
This issue is concerning the updates made to the constrained SPS design tool in order to accommodate the STK data report results of the equatorial SPS configuration.

**Comment by darianvp** [comment]
The equatorial orbit configuration considered is inspired by the Brandhorst Lunar SPS system proposal studied in the earlier issues. An equatorial sps orbit is chosen to target a rover at 45N latitude. The altitudes of the orbits considered are limited to the range of the south pole study (10-5000 km), based on the application of the pointing error and minimum power requirement constraints to the WPT link.

The processed results of this parametric scan are:

[MeanMaxRange_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179502/MeanMaxRange_Equatorial_IncrementedRes.txt)
[MeanMinRange_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179503/MeanMinRange_Equatorial_IncrementedRes.txt)
[MeanRange_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179505/MeanRange_Equatorial_IncrementedRes.txt)
[MeanStoredPowerEvent_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179506/MeanStoredPowerEvent_Equatorial_IncrementedRes.txt)
[TotalActive_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179507/TotalActive_Equatorial_IncrementedRes.txt)
[TotalBlackout_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179508/TotalBlackout_Equatorial_IncrementedRes.txt)
[TotalStoredPowerEvent_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179509/TotalStoredPowerEvent_Equatorial_IncrementedRes.txt)
[MaxActive_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179510/MaxActive_Equatorial_IncrementedRes.txt)
[MaxBlackout_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179511/MaxBlackout_Equatorial_IncrementedRes.txt)
[MaxStoredPowerEvent_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179512/MaxStoredPowerEvent_Equatorial_IncrementedRes.txt)
[MeanActive_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179513/MeanActive_Equatorial_IncrementedRes.txt)
[MeanBlackout_Equatorial_IncrementedRes.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2179514/MeanBlackout_Equatorial_IncrementedRes.txt)

The unconstrained design space generated from this data:

![equatorial_sps_design_jul10](https://user-images.githubusercontent.com/38875772/42498693-24598ef8-842d-11e8-9e43-f515a28908b4.png)

Due to the mismatch between the orbital inclination and the target location, some low altitude orbits cannot access the target. As a result these orbits are removed from the total access time and total power delivered design spaces. The blackout duration at the target for these orbits are assumed to be the same as the eclipse events. 

Overall this design configuration has a much lower active time than the south pole target / polar sps orbit. This is a combination of the target/orbit inclination mismatch and the fact that the equatorial SPS spends significantly more time eclipsed than the polar sps, especially when within range of the target.

The maximum blackout duration has a strange behaviour, however the total blackout duration takes a smooth predictable shape (total blackout decreasing as altitude increases):

![equatorial_sps_total_blackout_jul10](https://user-images.githubusercontent.com/38875772/42498956-dccd443e-842d-11e8-8f70-7428f48e95e1.png)

When applying the constraint for maximum allowable blackout duration, the gradient is revealed which shows that the maximum blackout duration is increasing with orbit altitude. My hypothesis here is that the lower altitude orbits, with shorter orbital periods, revisit the target faster and thus break up potential long blackout periods faster.

![equatorial_sps_design_jul10_maxblakout](https://user-images.githubusercontent.com/38875772/42499327-c1803708-842e-11e8-86df-fe89ffc3df32.png)

The plot shows that the lowest altitude (shortest period) above a certain threshold (approximately 1000 km) is the highest performing with respect to minimizing maximum blackout duration. My hypothesis is that this is because the revisit rate of the SPS is highest at this orbit (short period) while the the altitude of the orbit is still high enough to guarantee that the SPS will be properly sunlit while overhead the eclipsed target. I will investigate further in STK

**Comment by darianvp** [comment]
Maximum blackout is related to the alignment of the orbit perigee with the target longitude leading to very short access periods which occur within the eclipse duration of the SPS:

![equatorial_sps_blackout_cusp](https://user-images.githubusercontent.com/38875772/42502150-9349ab06-8435-11e8-9098-ff3950f70c3b.PNG)

Above is an example of 2 SPS with the following orbits:
SPS1 - 1100 km perigee, 2000 km apogee
SPS2 - 900 km perigee, 20000 km apogee

The blackout events at the target corresponding to these orbits are:

![equatorial_sps_design_jul10_maxblakout](https://user-images.githubusercontent.com/38875772/42502358-1725ac68-8436-11e8-95d1-2e64f0a9ee52.png)

By watching one of the maximum blackout duration events, I saw that the lower altitude orbit had short bursts of access, exclusively while eclipsed, whereas the higher altitude orbits had access while illuminated, thus breaking the blackout event. Around this ~1000 km threshold, the gradient in maximum blackout duration is extremely high for these reasons.

**Comment by darianvp** [comment]
Due to the regular eclipsing of the SPS in an equatorial orbit, the utility of a battery for WPT is higher than in the case of the polar orbit (where the eclipsing is more irregular). Furthermore, the maximum event duration for which stored powered would be necessary in order to maintain the WPT link seems to be generally shorter than in the case of the polar orbit, meaning a smaller battery would be required. 

In the case where only the pointing, power, and blackout requirements are applied for a SPS-Sorato link, a battery of 40 kg, charged fully for each stored power event, could reduce total blackout period by nearly 4% (an almost 50% increase in active time).

**Comment by darianvp** [comment]
The SPS design tool structure is roughly demonstrated in this flow diagram

![sps_design_optimization_fd](https://user-images.githubusercontent.com/38875772/42619888-9b5d7f22-85b9-11e8-865e-27924b3690c4.jpg)

**Comment by darianvp** [comment]
Shifting focus onto adding SPS constellations into script. Therefore I am passing this issue to @MatthewGrim for peer review.

**Comment by darianvp** [comment]
![sps_design_optimization_fd 1](https://user-images.githubusercontent.com/38875772/43004900-6c166d86-8c31-11e8-8633-bfa0d2984153.jpg)

**Comment by MatthewGrim** [comment]
@darianvp My only comment - I think the point where maximum blackout durations is going to become exceeding large can be show with some geometry:

![screenshot from 2018-07-23 11-43-33](https://user-images.githubusercontent.com/14801964/43063711-e5670b46-8e5c-11e8-9263-0585420f6eb2.png)

This should come out at something like 720km which is roughly where the boundary in your first domain seriously spikes.

In any case, this issue has shown the general behaviour of the equatorial simulations so I am closing the issue.
