### ISSUE TITLE
Check Approximation for Change in Orbital Elements

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#19]
In this issue I check to see if a first-order approximation for the rate of change of the orbital elements of the lunar SPS orbits is useful by comparing to the actual change in orbital elements as determined in STK.

**Comment by darianvp** [comment]
First test case: 100 km X 2000 km lunar polar orbit. The perturbations due to the oblateness of the Moon lead to a large drift in the argument of perigee of the orbit. This is not desirable for the elliptic orbit since the total active time of the system would likely increase (somewhat) if the argument of perigee was held constant over the target at the south pole.

In STK, the oblateness perturbations, up to order 4, result in the following change in eccentricity (first plot) argument of perigee, semi-major axis and inclination (second) over two years: 

![perturbed_ecc_100x2000km](https://user-images.githubusercontent.com/38875772/42809997-2fe53ada-89b7-11e8-8f6f-fb043ed5766f.jpg)
![perturbed_inertial_orbital_elements_100x2000km](https://user-images.githubusercontent.com/38875772/42809999-3001d744-89b7-11e8-9b4d-b77ecd34b6c8.jpg)


The total change in argument of perigee is roughly -124 degrees, whereas the other elements do not change. The rate of change of omega appears constant for this case. Analytically, this rate of change (defined by spherical harmonics up to order 3) is defined by:

![dwdt_oblatenes](https://user-images.githubusercontent.com/38875772/42809554-2db6c5ea-89b6-11e8-919c-4e43e82eced5.PNG)

According to Park and Junkins (ORBITAL MISSION ANALYSIS FOR A LUNAR MAPPING SATELLITE). Since the orbital elements except for argument of perigee are roughly constant, one would expect to see a relatively constant rate of change defined by the first term, with some superimposed oscillations. However the oscillations are third order and thus much smaller in magnitude than the second order constant term.

Note that the titles of these plots reference J2000 orbital elements, however the Inertial (moon-centric) frame is used.

**Comment by darianvp** [comment]
In comparing the results of these equations to the results from STK, the two are very different. The following is a plot of the calculated dw (in degrees) for the entire polar orbit design space, due to the oblateness of the Moon and the perturbations due to the Earth. The drift is dominated by the oblateness of the moon at low altitude, and the Earth's gravity at higher altitudes (a >> R)

![dwdt_southpoleconfig](https://user-images.githubusercontent.com/38875772/42929737-36d9b78c-8b3b-11e8-9d07-796f31b1487d.png)

Equation for drift due to Earth, from Ely "Stable Constellations of Frozen Elliptical Inclined Lunar Orbits".

![dwdt_earth](https://user-images.githubusercontent.com/38875772/42929843-8d794238-8b3b-11e8-86ab-b03c5e379ac5.PNG)

**Comment by darianvp** [comment]
![compare_drift_rate_arg_peri](https://user-images.githubusercontent.com/38875772/42995131-5a25e014-8c10-11e8-8aad-e8438f8cfe3b.png)

![compare_drift_rate_arg_peri_zoom](https://user-images.githubusercontent.com/38875772/42995389-0a7c8832-8c11-11e8-8a7d-ac7dce1ccfd7.png)

![compare_drift_rate_arg_peri_norm](https://user-images.githubusercontent.com/38875772/42995980-8018a4b2-8c12-11e8-9282-fb95187b75e7.png)

![compare_total_drift_arg_peri_norm](https://user-images.githubusercontent.com/38875772/43000598-6036e7b6-8c22-11e8-945d-6c46030d4494.png)

Here I show a comparison of the drift rate in argument of perigee, due to the oblateness of the moon, according to the analytic model from Park and Junkins to what is determined from STK numerical simulations (Classical Orbital Elements data report).  Once the models converge to one another, the normalized difference (| |STK| - |Analytical| | / |STK|) hovers around 0.1.

The singularity in the second term of the drift rate equation of P&J for circular orbits is handled in the analytical model by setting dwdt = 0 for the case when e = 0. This is not exactly true since the first term does not diverge, however it is practically true in the sense that the argument of perigee for a circular orbit is not well defined. However the diverging behaviour is still present for very slightly eccentric orbits. However at higher eccentricities the analytic model compares well to the numerical simulations.

**Comment by MatthewGrim** [comment]
@darianvp - doing some research into the orbital element variations, I found [this student project ](https://upcommons.upc.edu/bitstream/handle/2099.1/15241/Memoria.pdf) which outlines a method for calculating the orbital perturbations for the Moon, on page 40. According to this analysis, the lunar perturbations are the dominant errors for the low altitude orbits up to 2000km, after which the Earth becomes more significant than J2 perturbations. At 10000km, the sun starts to take effect over J2.

The results in this work need to be checked, but they show the focus you're making on Earth and lunar perturbations in the parameter space we are considering is correct. There is some challenge to the validity of higher altitude orbits in the simulation range, that we might want to address.
