### ISSUE TITLE
Broken scripts

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#20]
This issue documents a few broken scripts - these don't work because the raw data needed is not stored on the repository. All the same it would be good to make these scripts work, as they show important results to do with blackout behaviour and battery storage. The scripts to fix are:

Lunar_SPS/005-DVP-Lunar_South_Pole_SPS/Check_Gradient_in_Blackout_Events.py
Lunar_SPS/007-DVP-SPS-Power-Storage/SPS_With_Power_Storage.py

**Comment by darianvp** [comment]
Corrected scripts mentioned above so they will work with data available in the repository
