### ISSUE TITLE
Formulating pointing error constraint correctly based on extreme cases

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#22]
Trying to find the correct way to apply the pointing error constraint based on the extreme cases (maximum and minimum range) as opposed to applying it based on the mean range.

**Comment by darianvp** [comment]
Up until now the pointing error constraint was applied based on the comparing the surface beam size to a minimum allowable beam size which accounts for pointing error, based on the mean range of the SPS in each orbit. The effect was removing lowest altitude orbits. However this version of the constraint does not account for the extreme cases and thus cannot guarentee the requirements would be met for all active events. Therefore a formulation based on the extreme cases is necessary. With that in mind I have reformulated the constraint so it is compares the surface beam size to the minimum allowable beam size for both the minimum and maximum ranges, rather than mean, for the SPS for ever orbit. The effect is opening a gap between low altitude and high altitude orbits (delta = 1.752 e -6):

![pointing error jul25](https://user-images.githubusercontent.com/38875772/43252705-789f6cce-90c3-11e8-81a0-03004fa0e248.png)

This conflicts with the previous defintion of the constraint, since the lowest altitude orbits would have been removed (delta = 1.5 e - 6)

![pointing error mean jul25](https://user-images.githubusercontent.com/38875772/43253117-79962040-90c4-11e8-95bc-7b827130252a.png)

Note that the pointing error constraint in each case was different for each plot. Since using the first pointing error constraint with the mean range (second case) lead to a single point design space (only 10 x 10 km orbit allowed).

If I apply all constraints simultaneously (comparing surface beam size to minimum allowable at the min, max, and mean ranges) I get the following (delta = 1.5 e -6):

![pointing error all jul25](https://user-images.githubusercontent.com/38875772/43253389-2282dcca-90c5-11e8-9302-e8b5ce576c20.png)

and (delta = 1.752e -6):

![pointing error all jul25](https://user-images.githubusercontent.com/38875772/43253494-62bdddc6-90c5-11e8-890d-7e54e6ae8620.png)

The inconsistency in the region which is removed is strange and likely associated with the different transmitter aperture size which is derived for each case. The most logical solution is to apply all the constraint to all cases simultaneously.

**Comment by MatthewGrim** [comment]
I am not sure that the mean should be necessary for this analysis. The minimum, and maximum range should be sufficient for the constraint. This is because these two are a sufficient condition to know if the range has exceeded the bounds of the acceptable region where the transmitted beam is bigger than the required beam radius. This can be shown by plotting out the governing equations. I'm not sure what's gone wrong here?

**Comment by MatthewGrim** [comment]
In any case, I think the current implementation of the constraint works so am going to close this issue.
