### ISSUE TITLE
Generate plots for paper

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#23]
This issue documents the writing of scripts to produce plots for the conference paper. These are recorded so that anyone can easily reproduce them.

**Comment by MatthewGrim** [comment]
# Final adjustments to plots
The plots for the IAC are in pretty good shape, but there are a few edits that may be necessary. The main one is to sort out the receiver efficiencies that I am using. I say 10% to be conservative in the paper, but this is really to cover for losses due to no tracking of the satellite. The 10% is arbitrary, though there is a paper that says it should be 1.0 / 1.57-ish:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.466.5980&rep=rep1&type=pdf

Maybe I should use this number, and also apply it to the laser SPS efficiency? This might leave me open to less criticism, but I'm not sure if the number applies in both situations and across an arbitrary orbit.

**Comment by MatthewGrim** [comment]
Having tested the optimiser a little more - I'm more confident the results are as they should be.

**Comment by MatthewGrim** [comment]
# Update on plots
## Removal of tracking
After a lot of changes, we have removed the tracking analysis from the paper plots. This is because I am not confident that the assumptions I make in the analysis is valid. This will be pursued in further work.

## Energy storage
The energy storage analysis that I carried out, actually revealed that the Sorato cannot survive the lunar night with its battery, and maximum charging power. This needs to be incorporated as a constraint into the design tool, so that I can optimise the AMALIA rover.

## Using the new data set for Equatorial orbits
We could in theory use the new data set for equatorial orbits. Which might make the plots a little clearer as we wouldn't simulate orbits as low as 10km. This was a mistake to do in the first place, and might be confusing for the reader.

## Include South Pole to see if Sorato can work
Just for peace of mind, I want to do this analysis, but I can't for a like-for-like study until the new North pole data set is finished running. When it has, I can check, but I may only be able to add this after the paper is submitted.

**Comment by MatthewGrim** [comment]
In terms of adding energy storage as a constraint, I can't because this is dependent on the rover system being used. I would need to generate a different set for the AMALIA and Sorato cases.

The only way to do this is in a separate script from the main process_orbits function.

**Comment by MatthewGrim** [comment]
# Rover Survival Plots
## Sorato
![sorato_survival](https://user-images.githubusercontent.com/14801964/45586530-0ed4e180-b8f9-11e8-9f64-17b72877a46b.png)

## AMALIA
![amalia_survival](https://user-images.githubusercontent.com/14801964/45586531-17c5b300-b8f9-11e8-8013-74c353ddf740.png)

This shows more thought needs to be put into how to make the Sorato rover survive the lunar night. It's charging to hibernation power ratio and energy capacity ratio are not high enough.

**Comment by MatthewGrim** [comment]
## Optimised orbit for 1700km
Hacking the code of the design tool to force the removal of orbits below 1700km, this is the output:

Optimising transmitter radius
Iteration: 0, Max radius: 1.128
Iteration: 1, Max radius: 1.0151999999999999
Iteration: 2, Max radius: 0.9136799999999999
Iteration: 3, Max radius: 0.8223119999999999
Iteration: 4, Max radius: 0.7400808
0.284764948165 Solution found.
-----------------------------------------------------------------------------------------------------------
Optimal orbit altitudes --> Perigee: 1700.0 km, Apogee: 1700.0 km
Orbital period --> 301.32 minutes
-----------------------------------------------------------------------------------------------------------
Minimum allowable transmitter power --> 9.79 kW
Mean flux at receiver --> 0.22 AM0
Maximum flux at receiver --> 0.25 AM0
Minimum flux at receiver --> 0.18 AM0
-----------------------------------------------------------------------------------------------------------
Mean link efficiency --> 2.48743 %
Mean power delivered --> 121.73 W
Mean heat load on receiver --> 121.73 W
Total energy transferred --> 0.01 MJ per year
-----------------------------------------------------------------------------------------------------------
Transmitter aperture radius: 28.48 cm
Combined mass of generator and transmitter --> 533.22 kg
Combined heat load of generator and transmitter --> 25.94 kW
Steady state temperature --> 67.63 Celsius
-----------------------------------------------------------------------------------------------------------
Estimated argument of perigee drift rate --> 109.08 deg/yr
Estimated delta v available to correct drift with EP --> 5.5 km/s
Estimated delta v required to negate drift --> 0.0 km/s
NOTE: Circular orbit, correction of argument of perigee drift practically not necessary
-----------------------------------------------------------------------------------------------------------
Total active time (blackout reduction) --> 8.17 %
Total blackout time --> 41.59 %
Max active period duration --> 0.0 hours
Max blackout period duration --> 4.99 hours
-----------------------------------------------------------------------------------------------------------
Max event duration during which SPS requires stored power --> 1.26 hours
Approximate battery mass required to eliminate max duration event --> 4.55 kg
Approximate fuel cell mass required to eliminate max duration event --> 2.88 kg
Total time blackout time which could be eliminated with battery --> 4.13 %

**Comment by MatthewGrim** [comment]
The output above turned out to be incorrect - the final results are in the paper, and were validated by using the range analysis script on the 1700km circular orbit data

**Comment by darianvp** [comment]
@MatthewGrim 

Hypothetically it should be possible to increase the "rover survived area" simply by increasing the transmitter power. That way you charge the battery as much as possible during each active period. This is easily done by switching off the "optimize transmitter power" in the list of active constraints in the model. If the rover still can't survive with a 100kW laser, I would find that surprising.

However I have a suspicion that I'm not fully understanding what quantity is used to charge up the battery. My intuition tells me that it would be P_in - P_operation, but I'm not positive that this is what you have done.

Another possibility is to increase the relative amount of hibernating that the rover does. This isn't as straightforward to check. One quick way is by setting the operating power to:

P_op = a P_active + b P_hibernation

where a and b are the relative weightings of amount of time spent active and hibernating during the active beaming events.

**Comment by MatthewGrim** [comment]
I think this issue can finally be closed.
