### ISSUE TITLE
Write a script to fix the Equatorial Generic data set

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#31]
This issue documents a script that was written to fix two errors in the generic equatorial script:

1. Offset in EpSec in Access files
2. Large range files with more than statistics

**Comment by MatthewGrim** [comment]
The processing is done. Now what's left is to test the results against hand made simulations to make sure that there is not difference between the two sets. If that's the case, this data can be processed for the equatorial simulations.

**Comment by MatthewGrim** [comment]
## Bug in Perigee Angle - Radians should be Degrees!
This is a pretty monumental bug related to commit a127972 ... the argument of perigee has been specified in radians, when according to the documentation, it should be in degrees:
http://help.agi.com/stk/index.htm#../Subsystems/connectCmds/Content/cmd_SetStateClassical.htm

This means the equatorial simulations have to be re-run.

@darianvp can you confirm this is correct, and I deserve to be slapped?

**Comment by darianvp** [comment]
@MatthewGrim 

Yup it needs to be in degrees... Easy fix in the code just going to take some extra sim time.

Mean anomaly should also be in degrees I believe (for south pole)

**Comment by MatthewGrim** [comment]
With the new set running - I've compared two of the 2537.0 X 2537.0 simulations against simulations I made using the GUI. The results match or only differ in the last decimal place. This validates the new data set being generated, which should be much easier to process at least, because the units are now what is to be expected. Now all we need to do is wait.
