### ISSUE TITLE
Assess orbital stability of constellations

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#39]
Previous work has aimed to give an estimate of the orbital stability requirements on satellites in terms of a delta v requirement to maintain the orbit. This issue aims to continue the work by getting a more formal assessment of the orbital stability constraints from Ely-like analysis. This should hopefully clear up what we need to do to re-define the orbits based on the simple first pass that we have already done.

**Comment by MatthewGrim** [comment]
# Validate J4 against HPOP
The first thing I want to do is compare J4 perturbation results to those from HPOP, including Earth and Moon effects. I am going to do this for the extreme points from the parameter space (800km to 5000km) and also for the selected points in the rover optimisation.

**Comment by MatthewGrim** [comment]
# Results of Comparison - Equatorial
In these plots, orange is J4 and HPOP is blue

![equatorial 800km by 800km](https://user-images.githubusercontent.com/14801964/47554573-e550a200-d909-11e8-8dc9-6ae1933998f6.png)
![equatorial 800km by 5000km](https://user-images.githubusercontent.com/14801964/47554574-e550a200-d909-11e8-9e07-3489ec632318.png)
![equatorial 5000km by 5000km](https://user-images.githubusercontent.com/14801964/47554575-e550a200-d909-11e8-9519-52b570199b3b.png)

The results for equatorial show a maximum change in inclination of 14 degrees, while the sma is generally pretty stable. This stability requirement does not look so taxing to maintain.

**Comment by MatthewGrim** [comment]
# Results - Polar
![polar 800km by 800km](https://user-images.githubusercontent.com/14801964/47554676-2052d580-d90a-11e8-82a7-9c8628d7e4ac.png)
![polar 800km by 5000km](https://user-images.githubusercontent.com/14801964/47554677-20eb6c00-d90a-11e8-8b6a-9d7999f4d255.png)
![polar 5000km by 5000km](https://user-images.githubusercontent.com/14801964/47554679-20eb6c00-d90a-11e8-8f6a-8a756bfe4d8f.png)

Results in the polar case are more taxing. The 800 by 5000km orbit collides with the moon about a quarter of the way through the simulation (two years long). It's clear eccentricity is the main variable in this orbit and RAAN is also changing a lot. 

I haven't understood the significant of argument of perigee in this case. I should also be aware that these results are in the inertial frame.

**Comment by MatthewGrim** [comment]
# Correction to inclination of orbit
According to this [site](http://www.braeunig.us/space/orbmech.htm#maneuver) and [wikipedia](https://en.wikipedia.org/wiki/Orbital_inclination_change), the delta v to change inclination (eq. 4.73) is given by:

dV = 2 V_i * sin(theta / 2)

V_i = sqrt(GM / R) ~ 1kms^-1 at 6774km
sin(7) = 0.121
so the impulse would need to be 0.242kms^-1 for the circular 5000km orbit. This seems very low.

If I go down to 800km, the velocity hasn't changed considerably. The delta v to maintain this is pretty low. @darianvp does my calculation make sense to you?

**Comment by MatthewGrim** [comment]
LRO would have required [300m/s](https://space.stackexchange.com/questions/20583/are-low-polar-lunar-orbits-in-general-relatively-stable) for two years - we're in the right ball park :)

**Comment by MatthewGrim** [comment]
# Global Active Time Plots
What's going on with the 3 satellite orbits? The trend shows a local decrease...

![figure_1](https://user-images.githubusercontent.com/14801964/47567726-a3d2ed80-d92f-11e8-97dc-69a28d2fdb9d.png)

**Comment by MatthewGrim** [comment]
Observing satellites at 3000km by 5000km I can't see a drift of the satellites... I don't expect this anyway... I think I should look at the access times through time to see if they vary locally for some reason. 

This issue needs to be explained before we do system level analysis for the polar case.

**Comment by MatthewGrim** [comment]
Worth noting, the local reduction does not seem to go below (though I need to check) the two satellite case. It could be that the satellites genuinely show a slightly lower performance because of increased instability, but I would have thought I would have seen this in the 1 and 2 satellite cases.

**Comment by MatthewGrim** [comment]
This issue has thrown into question the results for polar orbit J4 perturbations. The equatorial results are fine, but to use the polar results, I need to demonstrate an appropriate frozen/stable orbit that we can use for providing access to the poles.

**Comment by MatthewGrim** [comment]
This issue is closed, and the assessment of frozen orbits will be dealt with in a separate issue.

**Comment by darianvp** [comment]
> # Global Active Time Plots
> What's going on with the 3 satellite orbits? The trend shows a local decrease...
> 
> ![figure_1](https://user-images.githubusercontent.com/14801964/47567726-a3d2ed80-d92f-11e8-97dc-69a28d2fdb9d.png)

Is it a true quantitative decrease in active time? Or simply a lack of improvement in adding a third satellite. Just looking at the plot it is very tough to say.
