### ISSUE TITLE
Build laser analysis model, and replicate figures 8 and 9 from the Brandhorst study

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#4]
This issue aims to complete the model infrastructure by modelling the power transmission link in the Brandhorst paper:

A Solar Electric Propulsion mission for lunar power beaming - H. W. Brandhorst et al.

The aim in this issue is to continue on from issue #3, by:
1. Writing a laser power transmission model. To do this, the relative position of the satellite to the target needs to be calculated, and used with the laser and receiver specification in the paper.
2. Replicate the laser intensity plot in figure 8.
3. Replicate the percentage area plot in figure 9.
3. Replicate the power delivered plot in figure 10.
4. Explain/Reason through any discrepancies.
(5. Explore the rest of the simulation parameter space - the figures are only plotting over a 3 day period)

**Comment by darianvp** [comment]
Examined the range data today and calculated the surface beam characteristics for comparison to Brandhorst. I exported a list of .csv from STK containing time stamps and distance from SPS1 to the target for all access times within the two year period (did not filter out periods when the SPS is in eclipse and target is illuminated). I calculated the surface beam size and flux, as well as the percentage of the receiver which is covered and the total power delivered. The calculations are based off the following transmitter/receiver metrics defined in Brandhorst:

Transmitter wavelength = 850 nm
Transmitter power = 40 kW
Transmitter area = 4 m2
Receiver area = 60 kW / (300 W/m2) = 200 m2
Receiver cell conversion efficiency = 45%

![receiver power coverage and surface beam flux brandhorst figs 8 and 9](https://user-images.githubusercontent.com/38875772/40059669-f99a5232-5854-11e8-83ff-1159794b2e7c.png)

The top left plot shows the SPS distance to target over time, the top right shows the surface beam flux relative to the nominal solar flux (1367 W/m2), the bottom left shows the percentage of the total receiver area which is covered, and the bottom right shows the total power received over time. In the bottom right plot, you can see the periods of no access.

I tried to do a direct comparison to the Brandhorst Figures 8, 9 and 10, which show the relative flux intensity and total receiver area covered (respectively) over the two day period Aug 18 2009 to Aug 20 2009, which corresponds to 414-416 days after the start of simulation (Jul 1 2008). However, the data which I produced via STK indicates that there is not an access period during those days. 

In general the results match relatively well to what Brandhorst presents. Namely the fact that the total surface beam flux minimum is 0.2 AM0, the minimum receiver area covered is ~2%, and the total power delivered is 18 kW. Results which are somewhat disputed are the maximum surface beam flux (2.2 AM0 is shown in Figure 8, and Brandhorst quotes in text that the max is 2 AM0, and my plot shows >6 AM0), the maximum receiver area which is covered (Brandhorst shows ~60%, makes no comment in text, but I find that it is ~90%), and the "power up" shown in Figure 10 (my plot shows that during access, constant 18 kW power is received).

The differences which remain may be a result of a slightly different orbit setup (indicated by the lack of access on Aug 14 - Aug 16 in my simulation). Another possibility is that Brandhorst filtered out instances when the SPS is eclipsed and target is illuminated. With respect to Figure 10, this shows that Brandhorst was likely considering the geometric effects of the SPS passes such that even during access time, zero power is transmitter from the horizon (cosine law for optics), although it is assumed in the paper that the receiver would track the SPS in at least one axis (azimuth). Will investigate these possibilities and post an update.

**Comment by darianvp** [comment]
These are the results with the SPS eclipse events and target illuminated events filtered.

![figs 8 and 9 filtered events out](https://user-images.githubusercontent.com/38875772/40065339-d523f84c-5861-11e8-8e75-e216366a7eff.png)

**Comment by darianvp** [comment]
Zooming in on a region [206, 217] (days) leads to a plot which reveals some of Brandhorst's insight. From the previous plot it appears that beam intensity can be as high as 6 times the flux received at the Sun. From this new plot, it is clear that those are brief opportunities which are interrupted by surface illumination or SPS eclipse events. Very broadly speaking, this new plot shows that the SPS can be used to provide power more-or-less continuously at a flux between 0.2 - 2 times the solar radiance.

![range-and-flux-beaming](https://user-images.githubusercontent.com/38875772/40369142-9ee0d3f0-5ddd-11e8-89a7-38669a4e3434.png)

Still big question mark regarding the relative area of the receiver which is covered ( i find max 80%, Brandhorst claims max 60%)

**Comment by MatthewGrim** [comment]
Nice catch on the surface beam flux point! As for the area coverage issue, I did the following back of the envelope for the maximum coverage at 30,000km, and get 83% coverage - more in line with your results.

There might be something to do with the angle of beaming, or type of laser, that we're not taking into account in our studies, but given that this is a validation exercise, I think we're good to go as long as we're consistent.

![screenshot from 2018-05-29 12-16-50](https://user-images.githubusercontent.com/14801964/40646564-d2e1a4c6-6329-11e8-905c-b8ffe2d0da0d.png)
