### ISSUE TITLE
Programattic Use of STK

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#6]
This issue is for files produced for controlling STK orbit simulations programmatically, so that large data sets, with varying object parameters, can be retrieved very quickly for parametric analysis of SPS architectures.

The first step is to set up a script which will produce a higher resolution data set for a problem already covered in another issue (#3 - calculating total access time as function of argument of perigee). Once the method is developed, it will be used to cover issue #5 - orbit optimization for maximum access time.

**Comment by darianvp** [comment]
Was able to create a script that generates a list of commands, which if executed sequentially, will change the spacecraft orbit and save .csv data file reports for the access time, lighting times, and eclipse times of the SPS. Just need to find a way to automatically copy and paste them into the STK Connect Command script window (since each new orbit requires 5 commands to change the object and generate the data).

**Comment by darianvp** [comment]
This result is relevant to this issue and to Issue #5.

I ran a parametric scan on the perigee and apogee of the elliptic orbit in the Brandhorst lunar SPS configuration, and calculated the resulting total active times for each orbit to assess the validity of Brandhorst's claim that the optimal orbit is one with a 500 km perigee altitude and 30000 km apogee altitude. The results are shown in the following plot, where apogee and perigee are measured relative to the focus of the orbit, not the surface of the moon (ie. an additional factor of 1737 km is added in comparison to the altitudes discussed by Brandhorst):

![brandhorst_orbit_design](https://user-images.githubusercontent.com/38875772/40907443-27e9ab1c-67e4-11e8-9d03-0eeee38aa72b.png)

One can see that as expected, the total active time for the SPS generally increases with altitude of the orbit. On the extreme right hand side, the active time drops to zero because of a small mistake in the data indexing during processing. This has been corrected in the script. 

The red 'X' shows the orbit design chosen by Brandhorst. The green 'o' shows the orbit which provides maximum SPS active time throughout the two year simulation. The active time offered by Brandhorst's orbit is 3535 hours, while the maximum in this parametric scan (resolution 250 km) is ~4600 hours (will update to exact value).

The unexpected part of this result is the oscillation between very high active times and relatively low access times for high apogee values. The oscillations appear to be mainly a function of apogee, with a slight dependance on the perigee resulting in the slant. To investigate whether the oscillations/stripes are a physical or digital result, we ran through another parametric scan with a different resolution to see if the same artifact would arise. For a 1000 km resolution for variations in perigee/apogee, we see the following:

![brandhorst_orbit_design_1000kmres](https://user-images.githubusercontent.com/38875772/40908936-81b8c05c-67e8-11e8-8f01-6de5c45197e0.png)

Resolution 1000 km --> Max total active time  4350 hours. Perigee 2737 km (minimum tested, corresponds to 1000 km altitude), Apogee 45737 km (44000 km altitude).

A similar artifact (dip in total active time) appears in the lower resolution plot as well. However, the finer detail in the 250 km resolution plot shows many more oscillations beginning at lower apogees. From some rough estimations made in the python workspace (printing out various active time values in the neighborhood of the max value, using the higher resolution data) the variation which leads to the "stripe" appears to be on the order of 600 hours, which is roughly a 10-15% fluctuation around the peak value. 

Interestingly, it looks like the main dip in active time shown in the lower res plot corresponds to the same dip/oscillation/stratification on which the maximum active time is found for the higher resolution plot.

**Comment by darianvp** [comment]
Adding onto the previous comment:

I have overlaid calculation of the power link efficiency to the total active time shown in the previous plot. Here the power link efficiency is defined as the ratio of the surface beam area to the receiver area, where the surface beam data is calculated via Gaussian beam divergence (see Issue #4).

For this first case which I have analyzed, the transmitter and receiver radii are:
Transmitter: 0.006 m
Receiver: 0.5 m
and the wavelength of the diverging beam is:
Wavelength: 1070 nm

These parameters are more or less a first guess, and will be fine tuned in further studies. Since the power link efficiency is a function of time and a function of orbit shape, the efficiency is averaged in time for evaluation of the power link performance as a function of orbit design. The results are as follows:

![brandhorst_orbit_design_1000kmres_linkeff](https://user-images.githubusercontent.com/38875772/41088003-9903cc2c-6a3e-11e8-8ecd-aa6e4129c7cb.png)

An "objective function" was formulated in order to assess the performance of an SPS orbit with respect to both the power link efficiency and total active time simultaneously. This function is defined as:

![codecogseqn](https://user-images.githubusercontent.com/38875772/41099254-396262a4-6a5e-11e8-8153-fbfe49a88c9c.gif)

Where eta is the mean link efficiency and T is the total active time for a given orbit. By definition, an orbit which results in f = 1 corresponds to simultaneous maximization of total active time and power link efficiency. The following is a plot of this function for this scenario, where the orbit which maximizes the function f is highlighted with a green X:

![brandhorst_orbit_design_1000kmres_active linkeff](https://user-images.githubusercontent.com/38875772/41099315-702a00c6-6a5e-11e8-9fe0-6e690992d859.png)

**Comment by darianvp** [comment]
In order to further investigate the strange behavior noted in the north-eastern corner of the plot which shows the total active time, Brandhorst (equatorial) configuration, another set of simulations was conducted with the time resolution in STK set much higher than in the previous case. The motivation behind this was that the oscillations may be a result of the time resolution in the STK calculations being comparable to access periods for certain sets of orbits.

Thus the time resolution was decreased from 60 mins to 5 mins, and a parametric scan across the region of interest ( > 5000 km perigee altitude, > 45000 km apogee altitude, using 500 km step resolution and the same maximum as previously). The following results were found:

![brandhorst_orbit_design_highertimeres_500kmres](https://user-images.githubusercontent.com/38875772/41103204-d8a07e0a-6a68-11e8-889e-6959bbb97793.png)

**Comment by darianvp** [comment]
Assigning this to @MatthewGrim to review the code and results

**Comment by darianvp** [comment]
An example of the solution to the constrained SPS orbit design problem, optimizing for maximal active time:

![sps_design_constrained](https://user-images.githubusercontent.com/38875772/41239030-c088a00e-6d97-11e8-8c5f-8e243894a21a.png)

    # Transmitter parameters
    wavelength = 850e-9
    trans_radius = 0.2
    trans_power = 100e3
    # Receiver parameters for AMALIA rover receiver
    rec_radius = 0.5
    rec_efficiency = 0.35
    # Pointing error in radians
    point_error = 1e-6
    # Minimum power received by rover
    min_power = 300.0

Best orbit --> Perigee: 10.0 km, Apogee: 4800.0 km
Total active time --> 2349.55 hours, or 13.39%
Link efficiency --> 0.87474%
Power received --> 306.16 W

In general, maximizing SPS active time leads to an orbit with the highest possible apogee, where the height is constrained by the power of the transmitter, and the lowest perigee. A new objective function should be formulated to account for link efficiency as well.

**Comment by darianvp** [comment]
[TotalBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2106574/TotalBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)

**Comment by darianvp** [comment]
@MatthewGrim 
Below are processed data files for total active, total blackout times, and mean range for parametric scan of polar orbits between 10 - 5000 km altitude.

[TotalBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2106578/TotalBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[MeanRange_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2106579/MeanRange_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[TotalActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2106580/TotalActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)

Example of SPS design space result, incorporating the following transmitter/reciever assumptions:
    # Transmitter parameters - IPG YLS10000 Industrial HP Laser
    wavelength = 1070e-9
    trans_radius = 0.1
    trans_power = 100e3
    trans_mass = 3600.0
    trans_eff = 0.35
    # Receiver parameters for AMALIA rover receiver
    rec_radius = 0.5
    rec_efficiency = 0.40
    # Pointing error in radians
    point_error = 1e-6
    # Minimum power received at target
    min_power = 100.0

![sps_design_jun15](https://user-images.githubusercontent.com/38875772/41476653-822dbcda-70c2-11e8-8ea0-da2410c34b95.png)

Generator and transmitter combined mass --> 5980.95 kg
Best orbit --> Perigee: 10.0 km, Apogee: 3200.0 km
Total active time --> 5046.19 hours, or 28.76%
Total blackout time --> 4165.15 hours, or 23.74 %
Link efficiency --> 0.25685%
Power received --> 102.74 W
Original target eclipse duration --> 53.0 %

**Comment by darianvp** [comment]
@MatthewGrim 
Incorporated an additional constraint on the maximum blackout duration. The constraint removes orbit design points for which the maximum blackout duration is greater than the maximum time for which a rover would be able to survive without recharging. This duration is determined by dividing the battery capacity by the minimum power consumption of the rover (hibernation mode). The max blackout duration appears to not be a simple monotonic function, whereas the total blackout, total active, max active, and mean link efficiencies are. Example:

![max_blackouts_jun18](https://user-images.githubusercontent.com/38875772/41523323-e012ad10-72d9-11e8-9662-41e6ba178a2e.png)

Therefore if this constraint is limiting enough, slices of the design space are removed. This is different than the other constraints (on spot size and power received) which cause a reduction in the design space from the edges. 

Including minimization of the max blackout duration in the weighted objective function leads to interesting results as well: 

![sps_design_constrained_jun18](https://user-images.githubusercontent.com/38875772/41523450-53939272-72da-11e8-8c85-08bbfaa64467.png)

Generator and transmitter combined mass --> 5980.95 kg
Best orbit --> Perigee: 10.0 km, Apogee: 3100.0 km
Total active time --> 4932.11 hours, or 28.11%
Max active period duration --> 2.96 hours
Total blackout time --> 4279.23 hours, or 24.39 %
Reduction in total blackout time --> 28.11 %
Max blackout period duration --> 4.57 hours
Link efficiency --> 0.27104%
Power received --> 108.41 W

Its difficult to say why the max blackout duration oscillates as a function of apogee altitude. It seems likely that the behaviour is related to the beat frequency of the orbital period and the moons period, causing some orbital configurations to spend extra time out of range of the target while illuminated, and eclipsed while in range of the target.

**Comment by MatthewGrim** [comment]
## Comments on issue so far
The oscillations in this issue need to be understood, both in blackout, and in active times. Opening up individual simulations and visualising the active times and blackout frequencies for comparison will probably make the reason for these stratifications more obvious.

In terms of the objective function, would it be more useful to ground the value in something more tangible than an averaging - maybe total energy received? This implicitly factors in link efficiency and active time, but it grounded in a value with meaning for the system. 

Just a check, have programmatic script results ever been checked against simulations done by hand? Just to make sure that they are consistent?

To my understanding, the mean link efficiency is not currently time averaged (it's just taking the mean of all access times) - is this not a problem?

**Comment by darianvp** [comment]
Plot along the peak stripe in the maximum blackout duration plot from previous comment. X is perigee radius (altitude + 1737 km) and Y is event duration. There is clearly variation in max blackout event duration as a function of perigee, but this does not show in the contour plot.

![max_blackouts_peak_jun18](https://user-images.githubusercontent.com/38875772/41542334-fbe26bc6-7314-11e8-815f-58a3d1cc85fa.png)

**Comment by darianvp** [comment]
[MeanBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2114613/MeanBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[MeanRange_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2114614/MeanRange_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[MeanActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2114615/MeanActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[MaxActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2114621/MaxActive_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)
[MaxBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt](https://github.com/MatthewGrim/Lunar_SPS/files/2114622/MaxBlackout_Inertial_Extended_SouthPole_IncrementedRes_Inertial.txt)

More data files to work with when testing the scripts. Updated the mean range so that it was averaged in time. Up till now I had been using an average of averages.

Previous data plots concerning the polar orbit configurations with incremented resolution in the orbital altitudes (dating back to June 11, 2018) had been incorrectly parsed and thus the results and visualizations are not correct.

**Comment by darianvp** [comment]
An example of the SPS design tool incorporating the power, pointing, and maximum blackout duration constraints. The objective function combines the effects of the total active time, mean blackout event duration, total energy delivered, and relative magnitude of orbital perturbations to determine the highest performing design. Furthermore this design space corresponds to the following smaller transmitter:

 # IPG YLS-CUT
wavelength = 1070e-9
trans_radius = 0.25
trans_power = 15e3
trans_mass = 440.0
trans_eff = 0.35

![sps_design_jun19](https://user-images.githubusercontent.com/38875772/41604316-361beb08-73df-11e8-81fd-c423dc4abf22.png)

Generator and transmitter combined mass --> 797.14 kg
Best orbit --> Perigee: 450.0 km, Apogee: 850.0 km
Total active time --> 2285.0 hours, or 13.02%
Max active period duration --> 0.86 hours
Total blackout time --> 6926.34 hours, or 39.48 %
Max blackout period duration --> 7.94 hours
Mean link efficiency --> 7.38664%
Mean power received per access period --> 443.2 W
Average power received throughout mission --> 1822.87 MJ per year

In general, increasing the transmitter size causes the left hand border to be pushed left. Increasing the target power requirement causes the right hand border to push in left. Depending on the weightings of the objective function, the optimal solutions are generally in the lower left hand corner or the lower right hand corner of the feasible design space, as these are the areas where link efficiency and active time are maximized, respectively.

**Comment by darianvp** [comment]
Moving on from this issue now that the scripts for generating, processing and visualizing data sets have been developed. @MatthewGrim can review and close the issue.

**Comment by MatthewGrim** [comment]
Clearly an understanding of programmatic SPS has been developed and used to understand the broad parameter space of SPS systems. 

Explaining the oscillations, and maximum blackout variations is an outstanding issue that we can tackle elsewhere. The main reason for doing this is to make sure we understand how the existence of what seems quite sporadic behaviour should be treated in SPS design.
