### ISSUE TITLE
Lunar South Pole SPS

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#7]
Studying the access periods and blackout periods for a solar power satellite targeting the lunar south pole

**Comment by darianvp** [comment]
Began study of SPS for Lunar south pole missions (rovers, landers, or bases). I based the original configuration off of a NASA paper by L. Johnson (Orbital space solar power option for lunar bases) where a 3000 km altitude polar orbit is proposed for an SPS servicing the south pole region.

First, I created a new STK scenario with this kind of satellite, and placed a target at -90 deg latitude, 0 deg longitude. Then I determined the total active time for the SPS over a two year period (for consistent comparison to the Brandhorst configuration) and the maximum blackout duration. The results are shown below. 

![active-blackouts-southpole-vs-circaltitude](https://user-images.githubusercontent.com/38875772/40366116-a58c5a96-5dd6-11e8-8516-a485843c027e.png)

The data point at 4000 km altitude minimizes the maximum blackout duration at the target (max 8.2 hours). However an interesting note can be made about the frequency of long blackout events. At 3000 km, the number of blackout events exceeding six hours is only 2, whereas at 4000 km it is 850. This huge difference certainly has to do with the threshold of six hours (half orbital period at 3000 km altitude is ~8 hours, and for 4000 km is ~11 hours). 

Then, I considered the possibility of flying the SPS in an elliptic orbit, with the apogee situated directly above the target. I considered a fixed perigee altitude of 300 km (arbitrarily chosen, but small for fast revisit rate at the south pole), and considered the same metrics as mentioned previously. 

![active-blackouts-southpole-vs-apogee](https://user-images.githubusercontent.com/38875772/40365015-eb26cd5a-5dd3-11e8-9891-8c5a9af742bc.png)

Clearly the advantage in terms of maximum blackout duration is in favor of the elliptic orbit. The maximum blackout duration is minimized for a apogee altitude of 15000 km (2.2 hour blackout). Furthermore, there is an advantage in long blackout frequency, since only one of the apogee data points considered in this study (5000 km) resulted in a blackout duration which exceeded six hours.  Blackouts for this configuration are typically on the order of 2 hours.

In all cases, the calculated maximum blackout duration without the service of the SPS was found to be on the order of 4000 hours (nearly half a year). This conflicts with general consensus in the field. Multiple papers have been published (eg. Illumination conditions at the lunar south pole using high resolution
Digital Terrain Models from LOLA from Gläser) which identify multiple lunar south pole sites with 70-95% illumination time. Small discrepancies exist in the position of these sites relative to the (-90,0) target I set in this analysis, but they are not large (~0.5 degree latitude). The majority of the difference in the blackout duration is likely to be a result of the topographical elevation data included in the analysis of Gläser and others which is not present in my STK model, which would influence line-of-site from the target to both the SPS and Sun.

**Comment by darianvp** [comment]
The target illumination conditions which I found are contradictory to what can be found in literature. For example, in P Gläser's paper "Illumination conditions at the lunar south pole using high resolution digital terrain models from LOLA', a site at -89.45 deg latitude and 222.69 deg longitude is identified as being illuminated 89.1% of the time. In general, Gläser identifies a number of sites on the south pole which are illuminated ~70-90% of the time. In my own analysis (using STK to look at illumination conditions at the aforementioned site), I find there exists an eclipse with duration >4000 hours, and as a result the illumination time at this site would be ~50%. When introducing the surface features of the lunar south pole in STK with LOLA data, the eclipse time increases (only slightly).

The reason that I am looking at this is that the results from the previous comment show that with an SPS servicing the lunar south pole, the duration of the maximum blackout period can be reduced by a factor of ~2000, compared to the scenario where solar-power is generated only on the surface. More importantly, the maximum blackout duration with SPS is on the order of 2-20 hours (depending on the orbit chosen) which is a realistic and manageable window for blackout conditions (whereas 4000 hours is not).

**Comment by darianvp** [comment]
Improved the resolution of the circular orbit plot from the previous comment slightly:

![active-blackouts-southpole-vs-circaltitude](https://user-images.githubusercontent.com/38875772/40541953-49dcb96c-601e-11e8-93fc-f78335ba479f.png)"

Furthermore, I calculated the maximum blackout event duration at the target, and the total time spent in blackout with and without the SPS support. These metrics are where I believe the SPS is the most valuable. Results for two year simulation, 3500 km altitude circular orbit SPS targeting south pole:

Total blackout duration w/o SPS: 9211 hours
Longest blackout w/o SPS: 4630 hours

Total blackout duration w SPS: 5590 hours
Longest blackout w SPS: 8 hours
Number of blackouts that exceed six hours: 2

Total time SPS is sunlit and in range: 6886 hours
Total SPS active time (when target eclipsed): 3622 hours

**Comment by MatthewGrim** [comment]
I still have to say I'm quite skeptical of these results still - the longest blackout shouldn't be half a year ... it'd be good to see the orbit simulations being run to make sure this isn't something to do with the simulation set up.

**Comment by darianvp** [comment]
I've run a parametric scan to try to find the lunar orbit which maximizes total SPS active time when targeting the south pole. This is done by varying the perigee and apogee of the orbit within the range of 1000 km (altitude) to 55000 km (altitude), using step sizes of 1000 km. The results for total active time (during a two year simulation) are shown in the plot below, with the maximum result denoted with a green dot. The maximum active time achievable was found to be ~4000 hours (23% of the simulation duration) for an orbit with a ~11000 km perigee altitude and ~55000 km apogee altitude.

![southpole_orbit_design](https://user-images.githubusercontent.com/38875772/40979808-29d5758e-68d7-11e8-8a74-a165cfc7aa4f.png)

**Comment by darianvp** [comment]
Closing this issue since the analysis of south pole target SPS merged with programmatic STK study (Issue #6) into the constrained SPS design tool in Issue #11.
