### ISSUE TITLE
Multi-Target SPS 

### ISSUE THREAD

**Issue by darianvp** [MatthewGrim/Lunar_SPS#8]
In this issue I will look into the characteristics of targeting multiple sites on the moon from a single SPS. The distribution of the targets can be latitudinal, or longitudinal. I hope to find a functional limit on the difference between target latitude and orbital inclination, and to evaluate a power distribution schedule.

**Comment by darianvp** [comment]
Here I begun the study by looking at the SPS access to a series of sites starting at the equator, separated in latitude by 12.5 degrees each up to 50 degrees, where the SPS is oriented in the equatorial plane. The results below show the range to target for the SPS during each access period, and the resulting surface beam flux assuming a 100kW transmitter with a 20 cm aperture diameter. The results are generated for both a circular 3000 km altitude orbit, and an 300 km, 15000 km altitude elliptic orbit.

![multiple_targets_rangeandflux](https://user-images.githubusercontent.com/38875772/40492822-a7190296-5f71-11e8-9473-6eaee3422e59.png)

![multiple_targets_rangeandflux_ellips](https://user-images.githubusercontent.com/38875772/40493290-b1d54900-5f72-11e8-9063-35ec7981bd0b.png)

Aside from the range/surface beam data, I also looked at the blackout periods at each target. For the circular orbit, the maximum blackout duration is around 6 hours at each target.

![multiple-targets-circle-blackouts](https://user-images.githubusercontent.com/38875772/40535994-0a058e6c-600b-11e8-9bbf-0fb16cdf1fb6.png)


For the elliptic orbit, the following trend is observed:

![multiple-targets-elliptic-blackouts](https://user-images.githubusercontent.com/38875772/40493420-ffb3e442-5f72-11e8-9a84-bd97abb52029.png)

Clearly the circular orbit has a large advantage when it comes to maximum target blackout duration. The fact that the elliptic orbit provides more power than the circular orbit at one point is interesting, likely a result of the extremely low perigee altitude. 

It seems to me that variation in latitude is the most important design variable for multiple targets (especially considering circular orbits which are symmetric in longitude).

**Comment by MatthewGrim** [comment]
From my perspective, the variations due to latitude are definitely important as well. You're showing that the close the target is to the equatorial plane, the better. 

Another issue that isn't being considered here though is the power requirements to beam to all of these targets at once. If there was one satellite that had the ability to beam to one target at a time, how far apart would the targets need to be spaced in longitude for the satellite to be able to service both at the same time? I think this, or similar questions, might be worth exploring as well.

**Comment by MatthewGrim** [comment]
I am closing this issue because it's been inactive for a month - any follow-on work based on the issues highlighted in the above comment should be addressed in a new issue.
