### ISSUE TITLE
Add basic pointing accuracy constraint to laser design tool

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#9]
In #2, a tool was developed for considering different laser systems, and whether they meet the constraints of the receiver and transmission architecture. This issue aims to add the constraint that the beam diameter must be sufficiently large that errors in pointing accuracy are tolerable, building on the analysis that has already been developed.

A basic constraint that can be applied is defined by the equations below:

![screenshot from 2018-05-28 16-45-52](https://user-images.githubusercontent.com/14801964/40615153-e3a30c68-6285-11e8-9554-b74759e06be4.png)

![screenshot from 2018-05-28 16-46-03](https://user-images.githubusercontent.com/14801964/40615158-e6c487f0-6285-11e8-8843-49c495f36aa4.png)

**Comment by MatthewGrim** [comment]
# Results of Script
![30w_results](https://user-images.githubusercontent.com/14801964/40618918-570365ba-6293-11e8-9eb9-bc1120ed0bcd.png)
![300w_results](https://user-images.githubusercontent.com/14801964/40618919-57221a96-6293-11e8-9ca1-6553686f975d.png)

Results make rough sense. The top left and far right can be removed because the power received gets too low. The middle section is removed because the pointing accuracy is too low.

**Comment by MatthewGrim** [comment]
Transferring this issue to @darianvp  for peer review.

**Comment by darianvp** [comment]
This result looks correct. I will be implementing the pointing error requirement in power link calculations in the future. Closing this issue now.
